# Generated by Django 5.2.15 on 2026-07-04 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anuncio',
            name='data_publicacao',
        ),
        migrations.RemoveField(
            model_name='anuncio',
            name='titulo',
        ),
        migrations.AddField(
            model_name='anuncio',
            name='produto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='marketplace.produto'),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='descricao',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='status',
            field=models.CharField(default='ATIVO', max_length=10),
        ),
        migrations.AlterModelTable(
            name='anuncio',
            table=None,
        ),
    ]
