# Generated by Django 5.2.15 on 2026-07-04 18:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_remove_anuncio_data_publicacao_remove_anuncio_titulo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anuncio',
            name='data_publicacao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
