# Generated by Django 5.2.15 on 2026-07-05 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_produtoimagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produtoimagem',
            name='ordem',
        ),
    ]
